### ISSUE TITLE
[iOS] Deep link handlers not called when app is fully closed

### ISSUE THREAD

**Issue by lucasroca** [AppsFlyerSDK/appsflyer-react-native-plugin#223]
## Plugin Version
`6.1.20`

## On what Platform are you having the issue?
iOS

## What did you do?
Installed the latest version of the plugin

## What did you expect to happen?
onDeepLink to be called

## What happened instead?
The handler wasn't triggered

## Please provide any other relevant information.
On iOS, react-native-appsflyer version 6.1.10, when clicking a OneLink the app opens but onAppOpenAttribution is not triggered when the app is fully closed.

Then I upgraded to react-native-appsflyer version 6.1.20 to test unified links. Again, works on every case except when the app is installed but fully closed and I open a OneLink.

I tried both on simulator and real device with no luck.

**Comment by Goldyukol** [comment]
Also problem, please fix this bag

**Comment by Voidozzer** [comment]
Same problem here

Plugin 6.1.20
React Native 0.63.3

Appears only on iOS, on Android works as expected.

**Comment by lucasroca** [comment]
Hi @amit-kremer93, do you have any updates on this?

**Comment by amit-kremer93** [comment]
For now, you can use `onInstallConversionData` listener to handle direct deep link in iOS by checking if 
`is_first_launch === false`. it's not the best solution but it will work until we figure it out

**Comment by rborn** [comment]
`onInstallConversionData` is not enough to get all the params. 
I had to downgrade to `6.0.50` to restore the behaviour :(

**Comment by Goldyukol** [comment]
> `onInstallConversionData` is not enough to get all the params.
> I had to downgrade to `6.0.50` to restore the behaviour :(

6.0.50 - does not work when the app is turned on :(
latest version - work when app on, but not work when start :(

**Comment by amit-kremer93** [comment]
@Goldyukol in which type of deep link do you use? URI scheme or universal link?

**Comment by Goldyukol** [comment]
> @Goldyukol in which type of deep link do you use? URL scheme or universal link?
> 6.0.50 works fine for me when the app in the background and when fully closed

In latest version this features doesn't work

**Comment by lucasroca** [comment]
> Did you follow [this](https://dev.appsflyer.com/docs/initial-setup-2)??
> For now, you can use `onInstallConversionData` listener to handle direct deep link in iOS by checking if
> `is_first_launch === false`. it's not the best solution but it will work until we figure it out

Yes, I've followed those steps. The issue still remains.



> @Goldyukol in which type of deep link do you use? URL scheme or universal link?
> 6.0.50 works fine for me when the app in the background and when fully closed

I'm using universal links.

**Comment by csantarin** [comment]
@amit-kremer93 like the rest of us here, definitely still happening on my end.

On relaunching the app, `onAppOpenAttribution` doesn't happen, but if it was running in the background, direct deep links would successfully trigger it.

**Comment by amit-kremer93** [comment]
It seems like the issue started after the native SDK was upgraded and we are working on a solution.
Sorry for the inconvenience.

**Comment by amit-kremer93** [comment]
I released a new version (6.1.40) with a fix for the onAppOpenAttribution in iOS. The implementation has slightly changed so please see [this](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#iosdeeplinks) but the flow is the same. Please let us know here if there is any problem. thanks!

**Comment by csantarin** [comment]
> Please let us know here if there is any problem.

@amit-kremer93 Yup, unfortunately, there is one.

`ML.Debug` refers to my local app process:

```txt
default	12:17:28.772654+0800	ML.Debug	[DEBUG] AppsFlyer: [HTTP] 
Result: {
    data = {length = 4, bytes = 0x226f6b22};
    dataStr = "\"ok\"";
    retries = 2;
    statusCode = 200;
    taskIdentifier = 3;
}                
Error: (null)
default	12:17:28.772732+0800	ML.Debug	[DEBUG] AppsFlyer: Loading conversion data
default	12:17:28.773572+0800	ML.Debug	[DEBUG] AppsFlyer: [GCD-A02] -[RNAppsFlyer onConversionDataSuccess:]:
{
    "af_message" = "organic install";
    "af_status" = Organic;
    "install_time" = "2021-01-18 04:06:20.689";
    "is_first_launch" = 0;
}
default	12:17:28.775784+0800	ML.Debug	[DEBUG] AppsFlyer: [CACHE] Deleting file: /var/mobile/Containers/Data/Application/1E631D5D-803D-4A15-8B56-FA65694DFF2D/Library/Caches/appsflyer-v1/632636244.2472.plist
default	12:17:28.775850+0800	ML.Debug	[DEBUG] AppsFlyer: [HTTP] Dealloc. Time elapsed for: `160-1610943444.211549` - 3.944231986999512
default	12:18:09.942508+0800	ML.Debug	*** Assertion failure in -[RCTEventEmitter sendEventWithName:body:](), /Users/csantarin/moneylion/mobile-app/node_modules/react-native/React/Modules/RCTEventEmitter.m:50
default	12:18:10.253181+0800	ML.Debug	*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: onAttributionFailure with body: {"status":"failure","type":"onAttributionFailure","data":"Authentication Failed"}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNAppsFlyer, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x1853619d8 0x1996cab54 0x18527050c 0x1865b9238 0x1051ecf80 0x1058948a8 0x1058946c8 0x186657614 0x1852e1bf0 0x1852e1af0 0x1852e0e38 0x1852db3e0 0x1852daba0 0x19c018598 0x187bca3d8 0x187bcf958 0x104604564 0x184fb9568)
```

**Comment by amit-kremer93** [comment]
@csantarin `{"status":"failure","type":"onAttributionFailure","data":"Authentication Failed"}` means that you have an issue with your devKey. about the crash, i released an hot fix.

**Comment by haipham-kontist** [comment]
I'm testing version `6.1.41`

- On android: it works in either scenarios, when app is in background, or when it's fully closed.
- On ios: it doesn't work if app is fully closed. It works if app is in background.

I already updated `didFinishLaunchingWithOptions`.

**Comment by Goldyukol** [comment]
> @ amit-kremer93 , тестирую версию`6.1.41`
> 
> * На Android: он работает в любом сценарии, когда приложение находится в фоновом режиме или когда оно полностью закрыто.
> * На ios: не работает, если приложение полностью закрыто. Работает, если приложение находится в фоновом режиме.
> 
> Я уже обновился `didFinishLaunchingWithOptions`.

How you updated `didFinishLaunchingWithOptions`? 

Send code pls

**Comment by haipham-kontist** [comment]
> How you updated `didFinishLaunchingWithOptions`?
> 
> Send code pls

You can find it in the updated guide: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#import

```
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
```

**Comment by Goldyukol** [comment]
> @amit-kremer93 , I'm testing version `6.1.41`
> 
> * On android: it works in either scenarios, when app is in background, or when it's fully closed.
> * On ios: it doesn't work if app is fully closed. It works if app is in background.
> 
> I already updated `didFinishLaunchingWithOptions`.

```
  [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];
```
added after?
```
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
```

**Comment by Goldyukol** [comment]
> I released a new version (6.1.40) with a fix for the onAppOpenAttribution in iOS. The implementation has slightly changed so please see [this](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#iosdeeplinks) but the flow is the same. Please let us know here if there is any problem. thanks!

Problem not resolved

**Comment by csantarin** [comment]
@Goldyukol not maintainer here. On `6.1.41`, I imagine it should look like this on a brand new `AppDelegate.m`:

```obj-c
#import <RNAppsFlyer.h>
#import <React/RCTLinkingManager.h>
#import <AppsFlyerLib/AppsFlyerLib.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Flipper init here...

  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];

  // React Native Bridge and Root View init here...
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] 
    initWithBridge:bridge
    moduleName:@"FiftyViewsUnderTheAppiumSea"
    initialProperties:nil
  ];

  // More on React Native Bridge and Root View init here...

  return YES;
}
```

Correct me if I'm wrong, @amit-kremer93. That's how I'm doing this on my end.

**Comment by csantarin** [comment]
> `{"status":"failure","type":"onAttributionFailure","data":"Authentication Failed"}` means that you have an issue with your devKey. about the crash, i released an hot fix.

Right you are, @amit-kremer93. But I've followed the iOS SDK / RN plugin integration guide. The `devKey` and `appId` are correct. So, I don't get it. Why would I have this issue?

On my end, `.initSdk(config)` is called right after subscribers, i.e. `onInstallConversionData`, `onAppOpenAttribution`, etc.

**Comment by jwebcat** [comment]
@amit-kremer93 we are also experiencing a similar issue. On the latest version of the plugin (`6.1.41`) for iOS if the app is fully closed, after tapping a onelink in the phones email client, the phone crashes with the following error

```
[DEBUG] AppsFlyer:                        
[Shortlink] OneLink:(null)                       
[Shortlink] Response Info:{
    data = {length = 21, bytes = 0x41757468656e7469636174696f6e204661696c6564};
    dataStr = "Authentication Failed";
    retries = 0;
    statusCode = 401;
    taskIdentifier = 1;
}                       
[Shortlink] Error: Error Domain=com.appsflyer.sdk.serialize Code=61 "Authentication Failed" UserInfo={NSLocalizedDescription=Authentication Failed}
```

Everything is setup according to the docs and was not crashing before updating the plugin (although onDeepLink was not firing on iOS). I have made the recommended changes from the new readme to the `AppDelegate.m` as well.

**Comment by colaquecez** [comment]
Same here, if i open the app and then i use deep link it works, but when the app is completely closed does not work :(

**Comment by csantarin** [comment]
@colaquecez @jwebcat @Goldyukol @haipham-kontist

I found something with the help of their support team that might help you out. 

```diff
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
+  [AppsFlyerLib shared].appsFlyerDevKey = @"YOUR_APPSFLYER_DEV_KEY";
```

For the app I work with, this was needed, on top of the `initSdk()` params. This isn't mentioned in the docs, though.

@amit-kremer93 I feel like this is a hack. Would it be possible to remedy this gotcha?

----

@amit-kremer93 The crash that I mentioned in https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223#issuecomment-761987345 is no longer there. There was a remnant code lying about (from `AppsFlyerFramework` `4.10.x` days) in `AppDelegate.m` > `application:applicationDidBecomeActive` that had to be removed from our codebase as it was causing all of those crashes:
```diff
(void)applicationDidBecomeActive:(UIApplication *)application {
  // Don't need the below.
-  [[AppsFlyerLib shared] start];
```

**Comment by amit-kremer93** [comment]
@csantarin 
`I feel like this is a hack, but it holds for the time being. Would it be possible to remedy this gotcha or at least make it known to everyone in the Init SDK guide?`
yes, you are right this is a workaround for now. it happened because of some improvements in the iOS SDK that launches faster than the plugin in react-native so we working on a long-term fix.

**Comment by rborn** [comment]
@csantarin thanks a lot for this. could you please explain where to put the code above? Because I don't have anything  similar to this in my appdelegate 🤗
```
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
+  [AppsFlyerLib shared].appsFlyerDevKey = @"YOUR_APPSFLYER_DEV_KEY";
 ```

**Comment by csantarin** [comment]
@rborn assuming latest React Native, in `application:didFinishLaunchingWithOptions`:

**AppDelegate.m**

```obj-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

// AppsFlyer imports
#import <RNAppsFlyer.h>
#import <AppsFlyerLib/AppsFlyerLib.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Flipper init here...


  // AppsFlyer init here...
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
  [AppsFlyerLib shared].appsFlyerDevKey = @"YOUR_APPSFLYER_DEV_KEY"; // HACK: iOS SDK is faster than RN plugin


  // React Native Bridge and Root View init here...
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] 
    initWithBridge:bridge
    moduleName:@"FiftyViewsUnderTheAppiumSea"
    initialProperties:nil
  ];

  // More on React Native Bridge and Root View init here...

  return YES;
}
```

Like in https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223#issuecomment-762352475, except you now have:

```obj-c
[AppsFlyerLib shared].appsFlyerDevKey = @"YOUR_APPSFLYER_DEV_KEY";
```

It's also in [the docs](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#-ios-deep-links---universal-links-and-url-schemes). Check it out.

**Comment by jwebcat** [comment]
@amit-kremer93 @rborn I have implemented the hacky workaround for plugin version `6.1.41` and now the `onDeepLink` handler is called and the app no longer crashes. There seems to be a new issue introduced however, the `onDeepLink` handler is not called intermittently both with the app fully closed and in the background. It works about 80% of the time. This makes me think perhaps a race condition is introduced with this latest workaround. This was tested on physical devices (iOS `13.1.2` and `14.4`) Is this happening for anyone else?

In the code below `af_dp` replaced with `xxx`

##### When the Onelink works and calls the `onDeepLink` handler the native logs show:

```
[DEBUG] AppsFlyer:                        
[Shortlink] OneLink:{
    "af_dp" = "xxx";
    "deep_link_value" = myProgram;
    "media_source" = Email;
    pid = Email;
}                       
[Shortlink] Response Info:{
    data = {length = 90, bytes = 0x7b227069 64223a22 456d6169 6c222c22 ... 22456d61 696c227d };
    dataStr = "{\"pid\":\"Email\",\"deep_link_value\":\"myProgram\",\"af_dp\":\"xxx\",\"media_source\":\"Email\"}";
    retries = 0;
    statusCode = 200;
    taskIdentifier = 5;
}                       
[Shortlink] Error: (null)
```

followed by 

```
[DEBUG] AppsFlyer: [GCD-A02] -[RNAppsFlyer onConversionDataSuccess:]:
{
    "af_message" = "organic install";
    "af_status" = Organic;
    "install_time" = "2021-01-27 21:51:15.073";
    "is_first_launch" = 0;
}
```

##### When the Onelink doesn't work and fails to call `onDeepLink` handler, the native logs only show:

```
[DEBUG] AppsFlyer:                        
[Shortlink] OneLink:{
    "af_dp" = "xxx";
    "deep_link_value" = myProgram;
    "media_source" = Email;
    pid = Email;
}                       
[Shortlink] Response Info:{
    data = {length = 90, bytes = 0x7b227069 64223a22 456d6169 6c222c22 ... 22456d61 696c227d };
    dataStr = "{\"pid\":\"Email\",\"deep_link_value\":\"myProgram\",\"af_dp\":\"xxx\",\"media_source\":\"Email\"}";
    retries = 0;
    statusCode = 200;
    taskIdentifier = 5;
}                       
[Shortlink] Error: (null)
```

In this case `[RNAppsFlyer onConversionDataSuccess:]:` is never called and it fails to call either the `onInstallConversionData` or `onDeepLink` handlers.

With the plugin version `6.1.20` it calls the `onDeepLink` handler successfully every time you tap a Onelink when the app is in the foreground, but is not called when the app is fully closed.

**Comment by curiousdustin** [comment]
I am also having this issue in version `6.1.41`. `onDeepLink` is only called if the app is already open. I have tried everything above including the "hack" from @csantarin, and it still does not work. 

I have tried on simulator and real device.

What else can I try?

**Comment by curiousdustin** [comment]
### AppDelegate.m
``` objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{  
  [Bugsnag start];

  // Firebase
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  // AppsFlyer
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
  [AppsFlyerLib shared].appsFlyerDevKey = [ReactNativeConfig envFor:@"APPSFLYER_DEV_KEY_IOS"];
  
  // Enable Logging For Release Builds
  // RCTSetLogThreshold(RCTLogLevelInfo - 1);
  
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"pinna" initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  return YES;
}
```

### My `setup()` function run as soon as possible:
``` js
static setup(handleAppsFlyerData) {
    let appsFlyerOptions = {
      devKey: APPSFLYER_DEV_KEY_IOS,
      appId: APPSFLYER_APP_ID_IOS,
      onInstallConversionDataListener: true,
      onDeepLinkListener: true,
      isDebug: true
    };

    if (handleAppsFlyerData) {
      onDeepLinkCanceller = appsFlyer.onDeepLink(res => {
        console.log('appsFlyer.onDeepLink', res);
        handleAppsFlyerData(res.data);
      });

      onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
        res => {
          console.log('appsFlyer.onInstallConversionData', res);
          if (
            res &&
            res.data &&
            res.data.is_first_launch &&
            JSON.parse(res.data.is_first_launch) == true
          ) {
            handleAppsFlyerData(res.data);
          }
        }
      );
    }

    if (Device.isIos) {
      // Do not need to call this when using the AppsFlyer SDK with IDFA removed
      // appsFlyer.disableAdvertisingIdentifier(true);
      appsFlyer.disableCollectASA(true);
    }

    appsFlyer.initSdk(
      appsFlyerOptions,
      result => {
        debug.log('appsFlyer.initSdk', result);
      },
      error => {
        debug.log('appsFlyer.initSdk ERROR', error);
      }
    );
  }
```

**Comment by amit-kremer93** [comment]
@jwebcat @curiousdustin if you want to use unified deep link instead of onAppOpenAttribution, try to replace
`[[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];`
with `[[AppsFlyerLib shared] setDeepLinkDelegate:_AppsFlyerdelegate]`

**Comment by curiousdustin** [comment]
@amit-kremer93 , that seems to have worked for me. Thanks!

You say replace. Is there any reason we should also keep the `setDelegate` line as well?

**Comment by jwebcat** [comment]
@amit-kremer93 after implementing the following, there is no change: 

> @jwebcat @curiousdustin if you want to use unified deep link instead of onAppOpenAttribution, try to replace
> `[[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];`
> with `[[AppsFlyerLib shared] setDeepLinkDelegate:_AppsFlyerdelegate]`

The same issue that I described persists (`onDeepLink` only fires ~80% of the time both with the app in the background and fully closed.)

**Comment by amit-kremer93** [comment]
@curiousdustin it can cause conflicts with these two listeners. if you want to use `onAppOpenAttribution` you must use `setDelegate` and if you want to use `onDeepLink` you must use `setDeepLinkDelegate`.
@jwebcat it happens randomly? or in certain flows? all this issue began because of performance and timing problems in React-Native and iOS, so try to call
`if(_AppsFlyerdelegate == nil){
   _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
}
[[AppsFlyerLib shared] setDeepLinkDelegate_AppsFlyerdelegate];
[AppsFlyerLib shared].appsFlyerDevKey = @"YOUR_APPSFLYER_DEV_KEY";`
at the top of your `didFinishLaunchingWithOptions`

**Comment by jwebcat** [comment]
@amit-kremer93 I already tried moving it to the top of `didFinishLaunchingWithOptions` and it doesn't make a difference. 

With the previous version `6.1.20` the `onDeepLink` fires 100% of the time with the app in the background. It fails to call `onDeepLink` at all with the app fully closed.

With this version `6.1.41` `onDeepLink` only fires about 70% of the time. The rest of the time it just opens the app. It seems to consistently fail to call `onDeepLink` on the first press of a onelink. Sometimes it works several times, then fails to call `onDeepLink` on the 3rd or 4th press of a onelink. It seems to fail as described for all scenarios / flows (app in the background and fully closed). This behavior for me points to a race condition of some sort, especially because in the previous version of the plugin it works as expected with the app in the background.

This issue is blocking our team from utilizing this feature. Any update on an actual fix would be much appreciated.

**Comment by rborn** [comment]
@amit-kremer93 any update on this? 🙏

**Comment by jwebcat** [comment]
@rborn this is fixed for us in plugin `v6.2.10`. I haven't tried the latest version that was just released.

**Comment by amit-kremer93** [comment]
@rborn as @jwebcat wrote, this issue was fixed in `v6.2.10` and also in the next releases

**Comment by rborn** [comment]
@amit-kremer93 @jwebcat thank you, will test today/tomorrow and let you know :)

**Comment by rborn** [comment]
@amit-kremer93 @jwebcat  Ok, tested with `"react-native-appsflyer": "6.2.31",` but the app still doesn't receive the deeplinks on cold start :( (ios)

**Comment by amit-kremer93** [comment]
@rborn please be sure you follow the new [docs](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#-ios-deep-links---universal-links-and-url-schemes)

**Comment by tomoakley** [comment]
I'm trying to implement Unified Deep Linking, but can't get `onDeepLinking` to fire when I run `xcrun simctl openurl booted https://mydomain.onelink.me/path/tolink` (which has a `deep_link_value` set in the creation UI). Launching the app via the URL scheme, i.e `xcrun simctl openurl booted myappscheme://test-deep-link` fires `onAppOpenAttribution` with the correct data in. I've been over the setup in the JS and Obj-C in AppDelegate.m multiple times and it all seems to be correct. I'm using the latest version of react-native-appsflyer (6.2.41) so I don't have any `setDelegate` or `setDeepLinkDelegate`. Here is the code I am using:

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
  [[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
  return YES;
}

// Reports app open from deep link from apps which do not support Universal Links (Twitter) and for iOS8 and below
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString*)sourceApplication annotation:(id)annotation {
  [[AppsFlyerAttribution shared] handleOpenUrl:url sourceApplication:sourceApplication annotation:annotation];
  return YES;
}

// Reports app open from URL Scheme deep link for iOS 10
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *) options {
  [[AppsFlyerAttribution shared] handleOpenUrl:url options:options];
  return YES;
}
```

```
  const onInstallConversionDataCanceller = (callback) =>
    appsFlyer.onInstallConversionData(callback)

  const onAppOpenAttributionCanceller = (callback) =>
    appsFlyer.onAppOpenAttribution(callback)

  const onDeepLinkCanceller = (callback) => appsFlyer.onDeepLink(callback)

  appsFlyer.initSdk(
    {
      devKey: Config.APPSFLYER_DEV_KEY,
      appId: '1265080577',
      isDebug: !isProdOrStage,
      onInstallConversionDataListener: true,
      openDeepLinkListener: true,
    },
    (result) => {
      console.log(`AppsFlyer initalised successfully: ${result}`)
    },
    (error) => {
      console.log(`There was a problem initalising AppsFlyer: ${error}`)
    }
  )
```
(the `callback` method's are passed in from another method. These shouldn't be a problem, for now they are just the standard ones in the docs).

**Comment by amit-kremer93** [comment]
@tomoakley please contact our support team: support@appsflyer.com

**Comment by jwebcat** [comment]
@tomoakley looks like in your `appsFlyer.initSdk` options, you need change `openDeepLinkListener: true` to be `onDeepLinkListener: true` then it should work as expected.

**Comment by rborn** [comment]
@amit-kremer93 I did 😅 and it seems that all works now, I forgot some delegate from the older versions in AppDelegate.m
Thanks for the help 😻

**Comment by tomoakley** [comment]
> @tomoakley looks like in your `appsFlyer.initSdk` options, you need change `openDeepLinkListener: true` to be `onDeepLinkListener: true` then it should work as expected.

thanks @jwebcat! I've changed it and now the `onInstallConversionData` callback is called, which wasn't happening before for unified deep links, but `onDeepLink` callback still isn't being called. I will contact the support team (unless anyone else spots anything).

**Comment by tomoakley** [comment]
update - I now get `onDeepLink` and `onInstallConversionData` called for launches via the URL scheme e.g `myapp://` but only `onInstallConversionData` for launching via a OneLink, `onDeepLink` callback does not get called.

**Comment by lucasroca** [comment]
I've updated to `6.2.41` and follow the [docs](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#-ios-deep-links---universal-links-and-url-schemes). My initial problem is solved now.

**Comment by eomttt** [comment]
@amit-kremer93  hello,     "react-native-appsflyer": "^6.3.20", always fire
onAppOpenAttribution method not called when ios app is fully closed

```swift
  func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool {
    AppsFlyerAttribution.shared().handleOpenUrl(url, options: options)
    return RCTLinkingManager.application(app, open: url, options: options)
  }

  func application(
    _ application: UIApplication,
    continue userActivity: NSUserActivity,
    restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
  ) -> Bool {
    AppsFlyerAttribution.shared().continueUserActivity(userActivity, restorationHandler: nil)
    return RCTLinkingManager.application(application, continue: userActivity) { _ in }
  }

  func application(
    _ application: UIApplication,
    open url: URL,
    sourceApplication: String?,
    annotation: Any) -> Bool {
    AppsFlyerAttribution.shared().handleOpenUrl(url, sourceApplication: sourceApplication, annotation: annotation)
    return true
  }
```

**Comment by maballe-melli** [comment]
hi guys, having issue with onDeepLink not getting called when in background. In my case, the onDeepLink is triggered if the app is fully closed. The issue only is when its in background. onInstallConversion does get called even when in background, but i cant get enough params.

Im running appsflyer 6.3.20. Testing in physical device running iOS 14.0.1. I have added domain association, my AppDelegate.m looks like this:

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <CodePush/CodePush.h>
#import <Firebase.h>
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
#import <React/RCTLinkingManager.h>
#import <RNAppsFlyer.h>
#import <AppsFlyerLib/AppsFlyerLib.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{  
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
  
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"melli"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  [RNSplashScreen show];

  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
  return YES;
}

//local push notification
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                                                 openURL:url
                                                 options:options];
  
  [RCTLinkingManager application:application openURL:url options:options];
  
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  
 [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];

  return YES;
}

@end

```

**Comment by maballe-melli** [comment]
![aaaa](https://user-images.githubusercontent.com/76741588/128111984-9dbc36c6-9529-46d5-b5f8-ea8940c390ae.PNG)

I have also tried following the code snippet suggested but im getting this error in xcode

**Comment by AlphaGit** [comment]
@maballe-melli In case you haven't been able to solve this yet (or for any other future visitors), that property needs to be declared so it can be used. That is done in the header file, so go to the `AppDelegate.h` file and inside the interface (between `@interface` and `@end`) add the following line:

```objectivec
@property (nonatomic) RNAppsFlyer *AppsFlyerdelegate;
```

**Comment by digocse** [comment]
Hi everyone!

I've been struggling with the same issue for some weeks while working with Flutter as you can see [here](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/issues/142#issuecomment-908633564).

The behavior is the same as @haipham-kontist mentioned:
- On android: it works in either scenarios, when app is in background, or when it's fully closed.
- On iOS: it doesn't work if app is fully closed. It works if app is in background.

I'm leaving this comment here just to warn you about this and try to help you isolate the problem. I think that the root cause is that there might be something happening with `application open url` method not being triggered by the time the app is closed.

I've already read a lot suggestions pointing to `scenes` in iOS but turns out that my project is only using `AppDelegate` and I already removed everything scene-related. 

Also, I created a side native project to test and it works just fine in all scenarios. The same behavior happens while opening the app through URL schemes. 

So I think this issue is not AppsFlyer related only. I believe those points reinforces the idea that we should probably focus our efforts on investigating the hybrid integration among `open url` method.

Does anybody knows if we should rely on any other method to make it work?

Thanks and hope this comment can help somebody else.

**Comment by jacprada** [comment]
@digocse thank you for the insight!

I am currently having the same iOS specific issue while trying to integrate a different react native library for push notifications and deep links. Your point on this not being an AppsFlyer related issue only finds confirmation from my side!

Sadly I do not have any tips to share on how to address this. 😢

**Comment by kamalpandey** [comment]
Having similar issue.

Any solution here?

**Comment by murilokrugner** [comment]
I'm having the same problem, still haven't found the solution?

**Comment by amit-kremer93** [comment]
Use latest version, clean your project and try again

**Comment by OrLevy23** [comment]
Issue happens to me when trying to click on deep link from a closed app.
looked at the native code and saw this error:
```AppsFlyer Debug: Error when sending event: onDeepLinking with body: {"status":"success","deepLinkStatus":"FOUND","data":{"show_screen":"edit_profile","campaign":"a","deep_link_sub1":"extra_values","af_dp":"tf1:\/\/edit-profile-picture","deep_link_value":"update_profile_picture","media_source":"User_invite"},"type":"onDeepLinking","isDeferred":false}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RNAppsFlyer, even though it's inherited from RCTEventEmitter.```

**Comment by ys-sherzad** [comment]
@amit-kremer93 
@OrLevy23 Hi there, did you find any solution. I'm facing the same problem on iOS, `onDeepLink` doesn't trigger when app is completely closed, but fires when app is in background.


`"react-native-appsflyer": "^6.9.2"`
`"react-native": "0.70.6"`

**Comment by OrLevy23** [comment]
So yes actually it appeared that this does not work in debug mode but only in release

**Comment by ys-sherzad** [comment]
@OrLevy23 Appsflyer doesn't work on debug mode, only for published apps. would you mind sharing your `AppDelegate.mm`? I have tried many things but no luck

**Comment by ys-sherzad** [comment]
Ok, it seems that this line was causing the issue

in `didFinishLaunchingWithOptions`
```
return [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
```

rewriting the above to the following seemed to have fixed the problem for me
```
[[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

return YES;
```

**Comment by OrLevy23** [comment]
So we have just noticed that this issue reconstructs for us. not sure whether this is a ios version specific issue (happens from ios 16 and above. currently struggling to test on older versions) or build issue.
Went back to the commit that I know for sure that it worked on but I can't seem to make the universal links to work from cold start.

**Comment by annasychugina** [comment]
Any ideas hot to fix it ?

I reproduced it on IOS v16 with UDL. 

After clicking on the link the application opens but the internal deeplink on current screen in the app does not work. It happened when app is fully closed

I've already tried this solution 

```
  if(_AppsFlyerdelegate == nil){
    _AppsFlyerdelegate = [[RNAppsFlyer alloc] init];
  }
  [[AppsFlyerLib shared] setDelegate:_AppsFlyerdelegate];
```

But it didn't help. The same behavior. Nothing changed. 

I use the latest version of `react-native-appsflyer`

```
  "react-native-appsflyer": "^6.9.4",
  "react-native": "0.65.3",
```

**Comment by OrLevy23** [comment]
@annasychugina is this something that used to work and stopped for you on iOS 16?

**Comment by annasychugina** [comment]
@OrLevy23 no, I didn't check it before. We started implementing UDL links (onelink) and I use onDeepLink method in the latest version of react-native-appsflyer. I didn't check previous versions . So, it doesn't work with cold boot (app opens but there is no redirect to current screen, onDeepLink isn't triggered) In the background everything works correctly.

Any solutions ? I tried everything which was mentioned here. So, think about not using onDeepLink method and start using Linking API (https://reactnative.dev/docs/linking)


But if you have any ideas and hacks how to fix (maybe it worked in previous version ?? because it's very strange, it's critical bug and yet there is no solution ). 

It doesn't work in IOS 14.0 and IOS >= 16.0  versions (I didn't check previous)

**Comment by annasychugina** [comment]
I also sent email to support.appsflyer.com but no answer

**Comment by trqvinh90** [comment]
Hi guys, are there any updates on this issue?

**Comment by OrenMag** [comment]
We have a similar issue on Both IOS and Android
Deferred deeplinking doesn't work - and sometimes even the when the app is in the background. Inconsistent bahaviour.
Any idea?

**Comment by paul-hart** [comment]
I am working on a former hybrid RN app that still had aspects of the code in Swift. Recently, while migrating Segment code, I broke AppsFlyer deeplinking and I was faced with the cold boot issue describe above. We had been using the Segment pod to import the dependency and now it's coming from the node_modules folder. The issue is a race condition between the iOS did open handler and the RN bridge being loaded. 

When the SDK was fully native it didn't care about a bridge! So calling the following would lead to the deeplink handler being called:

`AppsFlyerLib.shared().continue(userActivity, restorationHandler: nil)`

The first fix was to change it to:

`AppsFlyerAttribution.shared().continue(userActivity)`

This was ultimately the change the fixed it for me. However because we have more than one deeplinking solution in our app, I need it to return a boolean so that I know it's a valid AppsFlyer link. 

If you look at their code, it checks of the bride is loaded. 

```
- (void)continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^_Nullable)(NSArray * _Nullable))restorationHandler{
    if([self RNAFBridgeReady] == YES){
        [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
    }else{
        [self setUserActivity:userActivity];
    }
}
```

So if you are like me and need conditions around returning true, the following solution will work:

```
if AppsFlyerLib.shared().continue(userActivity, restorationHandler: nil) {
  if !AppsFlyerAttribution.shared().rnafBridgeReady {
    AppsFlyerAttribution.shared().continue(userActivity)
  }
      
  return true
}
```

What happens is the "AppsFlyerLib.shared().continue" function returns a boolean saying that the link applies to AppsFlyer. But because the bridge is not ready it does not get handled. Knowing the bridge is not ready using their boolean, calling "AppsFlyerAttribution.shared().continue" invokes "[self setUserActivity:userActivity]" which solves the race condition. 

When the bridge is ready, the AppsFlyerLib works fine. 

Honestly I find it very confusing there is both AppsFlyerLib and AppsFlyerAttribution. Also very annoying that the AppsFlyerAttribution version does not provide a boolean. 

In psudo code it's like this

```
if "can open apps flyer link, and will trigger the deeplink handler if app was backgrounded" {
  if "react native bridge is not ready" {
    "call function that would handle the link in a backgrounded situation but saves the activity for after the bridge is loaded"     
  }
  
  "return true because in either case we know we have an AppsFlyer link"
}
```

Hope this helps someone, this was very frustrating for me. Having two very similar instances of classes that have these subtle differences is very annoying. I am still confused by their SDK.

**Comment by CTOverton** [comment]
@paul-hart I'm facing a similar issue where in React Native my appsFlyer.onDeepLink function is only being called for deeplinks via URI scheme but not universal links. 

My AppDelegate.swift has this function implemented
```swift
  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Swift.Bool {
    var result = authorizationFlowManagerDelegate?.resumeExternalUserAgentFlow(with: url) ?? false

    if (!result) {
      AppsFlyerLib.shared().handleOpen(url, options: options)

      result = RCTLinkingManager.application(app, open: url, options: options)

      if (result) {
        UAMessageCenter.shared()?.defaultUI.dismissMessageCenter(animated: true);
      }
    }

    return result;
  }
```

I tried to add your suggestion to this function 
```swift
  func application( _ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void ) -> Bool {
      return RCTLinkingManager.application( application, continue: userActivity, restorationHandler: restorationHandler)
  }
```

But I have the error `AppsFlyerAttribution` is not found. Where would you be importing that from?

**Comment by paul-hart** [comment]
> @paul-hart I'm facing a similar issue where in React Native my appsFlyer.onDeepLink function is only being called for deeplinks via URI scheme but not universal links.
> 
> My AppDelegate.swift has this function implemented
> 
> ```swift
>   func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Swift.Bool {
>     var result = authorizationFlowManagerDelegate?.resumeExternalUserAgentFlow(with: url) ?? false
> 
>     if (!result) {
>       AppsFlyerLib.shared().handleOpen(url, options: options)
> 
>       result = RCTLinkingManager.application(app, open: url, options: options)
> 
>       if (result) {
>         UAMessageCenter.shared()?.defaultUI.dismissMessageCenter(animated: true);
>       }
>     }
> 
>     return result;
>   }
> ```
> 
> I tried to add your suggestion to this function
> 
> ```swift
>   func application( _ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void ) -> Bool {
>       return RCTLinkingManager.application( application, continue: userActivity, restorationHandler: restorationHandler)
>   }
> ```
> 
> But I have the error `AppsFlyerAttribution` is not found. Where would you be importing that from?

Just noticed this message sorry. It was from:
`import react_native_appsflyer`

**Comment by gsantiago** [comment]
Any news on this?

I'm facing the same problem. The deeplink doesn't work when the ios app is fully closed.

**Comment by gsantiago** [comment]
@annasychugina did you find a solution for this?

**Comment by vladimir-d-1** [comment]
guys, try add this:

   func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
....
        if let userActivity = connectionOptions.userActivities.first {
            self.scene(scene, continue: userActivity)
        }
    }

func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
        AppsFlyerLib.shared().continue(userActivity)
 }

**Comment by Falco26** [comment]
> guys, try add this:
> 
> ```
> 
>    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
> ....
>         if let userActivity = connectionOptions.userActivities.first {
>             self.scene(scene, continue: userActivity)
>         }
>     }
> 
> func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
>         AppsFlyerLib.shared().continue(userActivity)
>  }
> ```

Where did you add this?

**Comment by vladimir-d-1** [comment]
> > guys, try add this:
> > ```
> > 
> >    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
> > ....
> >         if let userActivity = connectionOptions.userActivities.first {
> >             self.scene(scene, continue: userActivity)
> >         }
> >     }
> > 
> > func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
> >         AppsFlyerLib.shared().continue(userActivity)
> >  }
> > ```
> 
> Where did you add this?

insert this into your SceneDelegate. Info about clicked deeplink pass into the app through connectionOptions param. Previously this info passed into AppDelegate didFinishLaunching... method.

**Comment by Falco26** [comment]
> This is caused by iOS functions (`application:open url` and `application:continue userActivity`) being called immediately after the app is opened and data being passed to `AppsFlyerLib` before React Native is initialized and the `openDeepLink` listener is set.
> 
> Switching to `AppsFlyerAttribution` actually waits for React Native to be initialized, then passed the data to `onDeepLink`, but unfortunately in Swift, due to the issue mentioned above ([#223 (comment)](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223#issuecomment-2032164160)) a double header bug was introduced recently, and now you can only import `AppsFlyerLib` which doesn't give you access to `AppsFlyerAttribution` and causes the `Cannot find 'AppsFlyerAttribution' in scope` error.
> 
> To get around this I added `#import "RNAppsFlyer.h"` to my `Bridging-Header` file, instead of importing anything into me AppDelegate. I was able to get access to `AppsFlyerAttribution` and everything worked as expected, including tapping on a deep link after force closing the app and `onDeepLink` being called. Hope this helps!
> 
> ### AppDelegate
> ```
>     func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>         AppsFlyerAttribution.shared().handleOpen(url, options: options)
>         return RCTLinkingManager.application(app, open: url, options: options)
>     }
>         
>     func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
>         // need to add custom handler to avoid type errors on restoration handler
>         let appsFlyerRestorationHandler: ([Any]?) -> Void = { restoredItems in
>             restorationHandler(restoredItems as? [UIUserActivityRestoring])
>         }
>         AppsFlyerAttribution.shared().continue(userActivity, restorationHandler: appsFlyerRestorationHandler)
>         return RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
>     }
> ```

@cvlehe could you please share your full implementation please?

**Comment by Jlexyc** [comment]
Hey guys, I've got the same issue. But solution from above to use `AppsFlyerAttribution` seems like helped. Thanks for sharing it @cvlehe , you've saved a lot of my time!

**Comment by cvlehe** [comment]
> > This is caused by iOS functions (`application:open url` and `application:continue userActivity`) being called immediately after the app is opened and data being passed to `AppsFlyerLib` before React Native is initialized and the `openDeepLink` listener is set.
> > Switching to `AppsFlyerAttribution` actually waits for React Native to be initialized, then passed the data to `onDeepLink`, but unfortunately in Swift, due to the issue mentioned above ([#223 (comment)](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223#issuecomment-2032164160)) a double header bug was introduced recently, and now you can only import `AppsFlyerLib` which doesn't give you access to `AppsFlyerAttribution` and causes the `Cannot find 'AppsFlyerAttribution' in scope` error.
> > To get around this I added `#import "RNAppsFlyer.h"` to my `Bridging-Header` file, instead of importing anything into me AppDelegate. I was able to get access to `AppsFlyerAttribution` and everything worked as expected, including tapping on a deep link after force closing the app and `onDeepLink` being called. Hope this helps!
> > ### AppDelegate
> > ```
> >     func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
> >         AppsFlyerAttribution.shared().handleOpen(url, options: options)
> >         return RCTLinkingManager.application(app, open: url, options: options)
> >     }
> >         
> >     func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
> >         // need to add custom handler to avoid type errors on restoration handler
> >         let appsFlyerRestorationHandler: ([Any]?) -> Void = { restoredItems in
> >             restorationHandler(restoredItems as? [UIUserActivityRestoring])
> >         }
> >         AppsFlyerAttribution.shared().continue(userActivity, restorationHandler: appsFlyerRestorationHandler)
> >         return RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
> >     }
> > ```
> 
> @cvlehe could you please share your full implementation please?

It's basically just as a I said previously. After you [install the AppsFlyer plugin](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/RN_Installation.md#installation-with-autolinking), open your project file in Xcode, add `#import "RNAppsFlyer.h"` to your [bridging header ](https://developer.apple.com/documentation/swift/importing-objective-c-into-swift) if using Swift, and then add the `AppsFlyerAttribution.shared()` code from above.

**Comment by dev-jaylim** [comment]
if someone still have problem with Objective-C, follow this. (*i got some hint from @cvlehe, and use translate Objective-C from Swift. )

previous

`
#import "AppsFlyerLib.h"

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
    
    [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
    return YES;
}
`

after
`
#import "AppsFlyerLib.h"
#import <AppsFlyerAttribution.h>

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
//  [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];

  typedef void (^AppsFlyerRestorationHandler)(NSArray<id<UIUserActivityRestoring>> * _Nullable restoredItems);

  AppsFlyerRestorationHandler appsFlyerRestorationHandler = ^(NSArray<id<UIUserActivityRestoring>> * _Nullable restoredItems) {
      restorationHandler(restoredItems);
  };
  
    [[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:appsFlyerRestorationHandler];
    return YES;
}
`

**Comment by dev-jaylim** [comment]
if someone still have problem with Objective-C, follow this. (*i got some hint from @cvlehe, and use translate Objective-C from Swift. )

previous

```
#import "AppsFlyerLib.h"

(BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {

[[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
return YES;
}
```

after
```
#import "AppsFlyerLib.h"
#import <AppsFlyerAttribution.h>

(BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
// [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];

typedef void (^AppsFlyerRestorationHandler)(NSArray<id> * _Nullable restoredItems);

AppsFlyerRestorationHandler appsFlyerRestorationHandler = ^(NSArray<id> * _Nullable restoredItems) {
restorationHandler(restoredItems);
};

[[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:appsFlyerRestorationHandler];
return YES;
}
```

**Comment by iway1** [comment]
I wish AppsFlyer team would implement these fixes themselves, I think they do not really maintain this SDK

**Comment by danielchan303** [comment]
> if someone still have problem with Objective-C, follow this. (*i got some hint from @cvlehe, and use translate Objective-C from Swift. )
> 
> previous
> 
> ```
> #import "AppsFlyerLib.h"
> 
> - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
> 
> [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
> return YES;
> }
> ```
> 
> after
> 
> ```
> #import "AppsFlyerLib.h"
> ++ #import <AppsFlyerAttribution.h>
> 
> - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
> // [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
> 
> ++ typedef void (^AppsFlyerRestorationHandler)(NSArray<id> * _Nullable restoredItems);
> 
> ++ AppsFlyerRestorationHandler appsFlyerRestorationHandler = ^(NSArray<id> * _Nullable restoredItems) {
> restorationHandler(restoredItems);
> };
> 
> ++ [[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:appsFlyerRestorationHandler];
> return YES;
> }
> ```

This doesn't work for me. The onDeepLink callback is not called even with this modification.

**Comment by muddsarHassan1** [comment]
No solution worked for me.

**Comment by arapocket** [comment]
I'm still getting this with 6.17.8
